import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {createInterface} from 'node:readline';
import {InvoicingClient,verifyInvoicingWebhook} from '../../../packages/invoicing-client/dist/index.js';
import {createService,drain} from '../src/worker.ts';
// Consumer uses the public built package and service, no CatalogPilot module.
test('independent public consumer: real PostgreSQL issuance, private PDF and signed events',async()=>{
 const child=spawn(process.env.INVOICING_TEST_PYTHON?'python':'uv',process.env.INVOICING_TEST_PYTHON?['tests/independent_bridge.py']:['run','--with','psycopg[binary]','python','tests/independent_bridge.py'],{env:{...process.env,PYTHONPATH:'tests'},stdio:['pipe','pipe','pipe']});let errors='';child.stderr.on('data',v=>errors+=v);let resolveReady,rejectReady;const ready=new Promise((r,j)=>{resolveReady=r;rejectReady=j}),queue=[],lines=createInterface({input:child.stdout});lines.on('line',line=>{const value=JSON.parse(line);if(value.ready)resolveReady();else{const pending=queue.shift();if(value.error)pending.reject(Error(value.error));else pending.resolve(value.value);}});child.on('exit',code=>{if(code)rejectReady(Error(errors));for(const q of queue)q.reject(Error(errors||'bridge_closed'));});const db=(op,request={})=>new Promise((resolve,reject)=>{queue.push({resolve,reject});child.stdin.write(JSON.stringify({op,request})+'\n')});
 const objects=new Map(),events=[],bucket={async put(k,v){objects.set(k,new Uint8Array(v))},async get(k){const data=objects.get(k);return data?{arrayBuffer:async()=>data.buffer}:null}};
 const workload={app_id:'second-consumer',token:'fixture-token',banksync_origin:'https://bank-fixture.example',banksync_token:'fixture-bank',bank_account_id:1,instance_id:'fixture-instance',consumer_id:'second-consumer',pairing_code:'0123456789',bank_secrets:['fixture'],webhook_keys:{current:'fixture-key'}};
 const env={ENVIRONMENT:'simulation',RPC_ORIGIN:'https://rpc-fixture.example',WORKLOADS_JSON:JSON.stringify([workload]),CALLBACK_HOSTS:'second-fixture.example',INVOICE_ARTIFACTS:bucket};let service,referenceCalls=0;
 const transport=async(input,options)=>{const r=input instanceof Request?input:new Request(input,options),u=new URL(r.url);if(u.hostname==='rpc-fixture.example'){const p=await r.json();return Response.json(await db(p.p_op,p.p_request));}if(u.hostname==='bank-fixture.example'&&r.method==='POST'){referenceCalls++;assert.equal((await r.json()).variable_symbol,'12345');return Response.json({error:'reference_conflict'},{status:409});}if(u.hostname==='bank-fixture.example')return Response.json({bank_observation_status:'healthy',bank_observed_through:null});if(u.hostname==='service-fixture.example')return service.fetch(r,env);if(u.hostname==='second-fixture.example'){const event=await verifyInvoicingWebhook({bodyBytes:new Uint8Array(await r.arrayBuffer()),headers:r.headers,appId:'second-consumer',keys:{current:{secret:'fixture-key'}}});events.push(event);return Response.json({ok:true,receipt_version:1,delivery_id:event.delivery_id});}throw Error('unexpected_external_request');};service=createService(transport);
 try{await ready;const client=new InvoicingClient({baseUrl:'https://service-fixture.example',token:workload.token,fetch:transport});const command={customer_id:'fixture',issuer_profile_id:'issuer',source_ref:'independent:one',kind:'one_off',currency:'CZK',lines:[{source_line_id:'1',description:'Externí testovací consumer - neplatit',quantity:'1',unit_minor:'100'}],delivery_policy:'automatic_customer_copy_owner'};const created=await client.createInvoice(command,'independent:one');assert.equal((await client.createInvoice(command,'independent:one')).invoice_id,created.invoice_id);await drain(env,workload,transport);const invoice=await client.invoice(created.invoice_id);assert.equal(invoice.issuance_state,'issued');assert.equal(invoice.artifact_state,'ready');assert.equal(invoice.outstanding_minor,'100');const pdf=await client.pdf(created.invoice_id);assert.equal(new TextDecoder().decode(new Uint8Array(await pdf.arrayBuffer()).slice(0,5)),'%PDF-');assert.ok(events.some(e=>e.event_type==='invoice.document_ready'));assert.equal((await client.billingStatus('fixture')).open_total_minor,'100');await db('fixture_banksync');const rejected=await client.createInvoice({...command,source_ref:'requested-conflict',variable_symbol:'12345'},'requested-conflict');await drain(env,workload,transport);const blocked=await client.invoice(rejected.invoice_id);assert.equal(blocked.number,null);assert.equal(blocked.issuance_state,'blocked');assert.equal(blocked.incident,'reference_conflict');assert.equal(referenceCalls,1);await drain(env,workload,transport);assert.equal(referenceCalls,1);}finally{if(child.exitCode===null){await db('close').catch(()=>{});child.stdin.end();await new Promise(r=>child.on('exit',r));}lines.close();}
});
