import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {writeFile,mkdir} from 'node:fs/promises';
import {PDFDocument} from 'pdf-lib';
import {renderInvoice,spayd} from '../src/render.ts';
import {companyLookup,normalizeIco} from '../src/companyLookup.ts';
const profile={party_type:'company',legal_name:'Fiktivní český subjekt',company_id:'00000001',tax_id:null,address_line:'Vzorová 12/3a',city:'Brno',postal_code:'60200',country_code:'CZ',email:'fixture@example.invalid'};
export const snapshot={simulation:false,brand_name:'CatalogPilot',number:'TEST-2026-000001',issued_on:'2026-10-04',due_on:'2026-10-18',issuer:profile,buyer:profile,owner_email:'owner@example.invalid',account:{iban:'CZ6508000000192000145399',physical_account_id:'test-only'},reference:{normalized_vs:'00012345',reservation_id:'test-only'},command:{customer_id:'fixture',issuer_profile_id:'issuer',source_ref:'external-fixture:qr',kind:'one_off',currency:'CZK',delivery_policy:'automatic_customer_copy_owner',lines:[{source_line_id:'x',description:'Výslovně testovací faktura - neposílat a neplatit',group_label:'Testovací e-shop',quantity:'1',unit_minor:'12345'}]},total_minor:'12345',tax_regime:'non_vat'};
test('Workerd renders the actual Czech multipage service PDF and exact SPAYD',async()=>{
 const s={...snapshot,command:{...snapshot.command,lines:Array.from({length:40},(_,i)=>({...snapshot.command.lines[0],source_line_id:String(i),description:'Dlouhý český název služby a nedělitelný token '+('d'.repeat(120)),group_label:i<20?'Testovací obchod A':'Testovací obchod B'}))},total_minor:'493800'};
 const maximum={...snapshot,command:{...snapshot.command,lines:Array.from({length:500},(_,i)=>({...snapshot.command.lines[0],source_line_id:String(i)}))},total_minor:'6172500'};
 const entry=`import {renderInvoice} from './src/render.ts';export default {async fetch(request){return new Response((await renderInvoice(new URL(request.url).pathname==='/maximum'?${JSON.stringify(maximum)}:new URL(request.url).pathname==='/simulation'?${JSON.stringify({...snapshot,simulation:true})}:${JSON.stringify(s)})).buffer,{headers:{'Content-Type':'application/pdf'}})}}`;
 const bundle=await build({stdin:{contents:entry,resolveDir:process.cwd(),sourcefile:'render-fixture.ts'},bundle:true,write:false,platform:'browser',format:'esm',target:'es2022'});
 const runtime=new Miniflare(convertV4MiniflareOptions({name:'renderer-fixture',modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2026-10-01',cf:false}));try{const r=await runtime.dispatchFetch('https://fixture/render');assert.equal(r.status,200);const bytes=new Uint8Array(await r.arrayBuffer()),pdf=await PDFDocument.load(bytes);assert.ok(pdf.getPageCount()>1);assert.equal(pdf.isEncrypted,false);await mkdir('../../private/invoicing-tests',{recursive:true});await writeFile('../../private/invoicing-tests/rendered.pdf',bytes);await writeFile('../../private/invoicing-tests/expected-qr.txt',spayd(s));const simulated=await runtime.dispatchFetch('https://fixture/simulation');assert.equal(simulated.status,200);await writeFile('../../private/invoicing-tests/simulation.pdf',new Uint8Array(await simulated.arrayBuffer()));const started=performance.now(),maxResponse=await runtime.dispatchFetch('https://fixture/maximum');assert.equal(maxResponse.status,200);const maxPdf=await PDFDocument.load(await maxResponse.arrayBuffer());assert.ok(maxPdf.getPageCount()<=100);assert.ok(performance.now()-started<30000,'500-row rendering exceeds local 30s wall-time budget');}finally{await runtime.dispose();}
});
test('preflight rejects unsupported glyphs, 0/501 rows and wrong exact totals',async()=>{for(const s of [{...snapshot,command:{...snapshot.command,lines:[]}},{...snapshot,command:{...snapshot.command,lines:Array(501).fill(snapshot.command.lines[0])}}, {...snapshot,command:{...snapshot.command,lines:[{...snapshot.command.lines[0],description:'Unsupported 😀'}]}},{...snapshot,total_minor:'12346'}])await assert.rejects(renderInvoice(s));assert.ok(spayd({...snapshot,simulation:true}).includes('NOT A PAYMENT'));});
test('official ARES mapping preserves identity, optional tax ID and address without street',async()=>{assert.equal(normalizeIco('00 00 00 01'),'00000001');assert.throws(()=>normalizeIco('1'));const r=await companyLookup('fixture','00000001',async()=>Response.json({ico:'00000001',obchodniJmeno:'Testovací firma',sidlo:{nazevObce:'Vesnice',cisloDomovni:12,cisloOrientacni:3,cisloOrientacniPismeno:'a',pscTxt:'00100',kodStatu:'CZ'},datumAktualizace:'2026-10-01'}));assert.equal(r.profile.company_id,'00000001');assert.equal(r.profile.address_line,'12/3a');assert.equal(r.profile.tax_id,undefined);await assert.rejects(companyLookup('fixture','00000002',async()=>Response.json({ico:'00000003',obchodniJmeno:'Wrong'})));await assert.rejects(companyLookup('fixture','00000004',async()=>new Response('',{status:429})),/unavailable/);});
