import type {BillingProfile} from '../../../packages/invoicing-client/src/index.ts';
const ORIGIN='https://ares.gov.cz/ekonomicke-subjekty-v-be/rest/ekonomicke-subjekty/';
const cache=new Map<string,{expires:number;value:Record<string,unknown>;notFound?:boolean}>();
const limits=new Map<string,{time:number;count:number}>();
export function normalizeIco(value:string){const ico=value.replace(/\s/g,'');if(!/^\d{8}$/.test(ico))throw Error('ico_invalid');return ico;}
function rate(key:string,max:number){const now=Date.now();let v=limits.get(key);if(!v||v.time<now-60000){v={time:now,count:0};limits.set(key,v);}if(++v.count>max)throw Error('lookup_rate_limited');if(limits.size>10000)limits.clear();}
export async function companyLookup(app:string,ico:string,transport:typeof fetch=fetch){ico=normalizeIco(ico);rate(app,20);rate('*',100);const prior=cache.get(ico),now=Date.now();if(prior&&prior.expires>now){if(prior.notFound)throw Error('company_not_found');return {...prior.value,stale:false};}
 try{const response=await transport(ORIGIN+ico,{redirect:'manual',signal:AbortSignal.timeout(5000),headers:{Accept:'application/json'}});if(response.status===404){cache.set(ico,{expires:now+300000,value:{},notFound:true});throw Error('company_not_found');}if(!response.ok)throw Error('registry_unavailable');
 const reader=response.body?.getReader();if(!reader)throw Error('registry_unavailable');let size=0;const chunks:Uint8Array[]=[];for(;;){const r=await reader.read();if(r.done)break;size+=r.value.length;if(size>131072){await reader.cancel();throw Error('registry_response_too_large');}chunks.push(r.value);}const bytes=new Uint8Array(size);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length;}
 const entity=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));if(entity.ico!==ico||typeof entity.obchodniJmeno!=='string')throw Error('registry_identity_mismatch');const s=entity.sidlo??{};
 const address=s.cisloDoAdresy??[s.cisloDomovni,s.cisloOrientacni?'/'+s.cisloOrientacni+(s.cisloOrientacniPismeno??''):''].filter(Boolean).join('');const country=s.kodStatu==='CZ'||s.kodStatu===203||s.kodStatu==='203'?'CZ':null;
 const profile:Partial<BillingProfile>={party_type:'company',company_id:ico,legal_name:entity.obchodniJmeno,address_line:[s.nazevUlice??s.nazevCastiObce??'',address].filter(Boolean).join(' '),city:s.nazevObce??'',postal_code:String(s.pscTxt??s.psc??''),...(country?{country_code:country}:{}),...(entity.dic?{tax_id:entity.dic}:{}),registry_source:'ares',retrieved_at:new Date(now).toISOString(),registry_updated_at:entity.datumAktualizace,field_origins:{legal_name:'registry',address_line:'registry',city:'registry',postal_code:'registry',company_id:'registry'}};
 const normalized=JSON.stringify({ico,name:profile.legal_name,address:profile.address_line,city:profile.city,postal:profile.postal_code,country,tax:profile.tax_id??null});profile.registry_hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(normalized)))].map(v=>v.toString(16).padStart(2,'0')).join('');
 const value={profile,source_url:ORIGIN+ico,retrieved_at:profile.retrieved_at,review_required:!!entity.datumZaniku||!country,unstructured_address:s.textovaAdresa??null,stale:false};cache.set(ico,{expires:now+86400000,value});if(cache.size>1000)cache.delete(cache.keys().next().value!);return value;
 }catch(error){if(prior&&!prior.notFound&&(error as Error).message!=='company_not_found'&&(error as Error).message!=='registry_identity_mismatch')return {...prior.value,stale:true};throw error;}
}
