import {verifyWebhook,extractReferenceCandidates} from '@festapp/banksync';
import {companyLookup} from './companyLookup.ts';
import {renderInvoice,RENDERER_VERSION,type Snapshot,type InvoiceBrand} from './render.ts';
import {signInvoicingWebhook} from '../../../packages/invoicing-client/src/index.ts';
import {awsRequest,type AwsEnv} from '../../../packages/email-transport/src/aws.ts';
import {sha256} from '../../../packages/email-transport/src/aws-sigv4.ts';
export interface Workload {app_id:string;token:string;banksync_origin:string;banksync_token:string;bank_account_id:number;instance_id:string;consumer_id:string;pairing_code:string;bank_secrets:string[];webhook_keys:Record<string,string>;email_from?:string;email_configuration_set?:string;feedback_queue_url?:string}
export interface Env extends AwsEnv {RPC_ORIGIN:string;RPC_APIKEY?:string;WORKLOADS_JSON?:string;BRANDS_JSON?:string;CALLBACK_HOSTS?:string;ENVIRONMENT:'simulation'|'live';LIVE_ACTIVATION?:string;INVOICE_ARTIFACTS?:R2Bucket}
export class RpcError extends Error {readonly status:number;constructor(status:number,code:string){super(code);this.status=status;}}
function httpsOrigin(value:string){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash||u.port)throw Error('invalid_origin');return u;}
export async function serviceRpc(env:Env,token:string,op:string,request:unknown={},transport:typeof fetch=fetch):Promise<any>{
 const r=await transport(new URL('/rest/v1/rpc/dispatch',httpsOrigin(env.RPC_ORIGIN)),{method:'POST',redirect:'manual',signal:AbortSignal.timeout(15000),headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json','Content-Profile':'invoicing_api','Accept-Profile':'invoicing_api',...(env.RPC_APIKEY?{apikey:env.RPC_APIKEY}:{})},body:JSON.stringify({p_op:op,p_request:request})});if(!r.ok){let code='rpc_unavailable';let status=r.status;try{const data=await r.json() as any;code=data.message??code;status=data.code==='23505'||data.code==='40001'?409:data.code==='P0002'?404:data.code==='42501'?403:data.code==='22023'?400:status;}catch{}throw new RpcError(status,code);}return r.json();
}
async function bounded(request:Request,max=65536){if(Number(request.headers.get('Content-Length')??0)>max)throw new RpcError(413,'payload_too_large');const reader=request.body?.getReader();if(!reader)return new Uint8Array();let n=0;const chunks:Uint8Array[]=[];for(;;){const r=await reader.read();if(r.done)break;n+=r.value.length;if(n>max){await reader.cancel();throw new RpcError(413,'payload_too_large');}chunks.push(r.value);}const all=new Uint8Array(n);let at=0;for(const c of chunks){all.set(c,at);at+=c.length;}return all;}
function workloads(env:Env):Workload[]{return JSON.parse(env.WORKLOADS_JSON??'[]');}
function active(env:Env){if(env.ENVIRONMENT==='live'&&env.LIVE_ACTIVATION!=='verified-configuration')throw new RpcError(503,'live_activation_required');}
export async function privatePdf(env:Env,artifact:any){if(!env.INVOICE_ARTIFACTS)throw new RpcError(503,'storage_not_configured');const obj=await env.INVOICE_ARTIFACTS.get(artifact.object_key);if(!obj)throw new RpcError(503,'artifact_missing');const data=new Uint8Array(await obj.arrayBuffer());if(await digest(data)!==artifact.sha256)throw new RpcError(503,'artifact_integrity');return data;}
async function digest(data:Uint8Array){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new Uint8Array(data).buffer))].map(v=>v.toString(16).padStart(2,'0')).join('');}
export async function banksyncReceive(request:Request,env:Env,transport:typeof fetch){
 const bodyBytes=await bounded(request),candidate=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bodyBytes));const w=workloads(env).find(w=>w.pairing_code===candidate.pairing_code);if(!w)throw new RpcError(403,'bank_mapping_unknown');
 let envelope:any;for(const secret of w.bank_secrets){try{envelope=await verifyWebhook({secret,bodyBytes,eventVersion:'2',timestamp:request.headers.get('X-BankSync-Timestamp')??'',deliveryId:request.headers.get('X-BankSync-Delivery-Id')??'',signature:request.headers.get('X-BankSync-Signature')??''});break;}catch{}}
 if(!envelope||envelope.data.bank_account_id!==w.bank_account_id)throw new RpcError(403,'bank_signature_or_scope');
 const candidates=extractReferenceCandidates(envelope.data),symbols=new Set(candidates.map((v:any)=>String(v.vs??v.value??v).replace(/^0+(?=\d)/,'')));envelope.data.reference_conflict=symbols.size>1;
 return serviceRpc(env,w.token,'bank_receive',{envelope,instance_id:w.instance_id,consumer_id:w.consumer_id,payload_hash:await digest(bodyBytes)},transport);
}
export function createService(transport:typeof fetch=fetch){return {
 async fetch(request:Request,env:Env){try{const url=new URL(request.url);if(url.pathname==='/health')return Response.json({service:'invoicing',version:1,environment:env.ENVIRONMENT});if(request.method==='POST'&&url.pathname==='/webhooks/banksync')return Response.json(await banksyncReceive(request,env,transport));
 const token=request.headers.get('Authorization')?.match(/^Bearer (.+)$/)?.[1];if(!token)throw new RpcError(401,'workload_required');const call=(op:string,data:unknown={})=>serviceRpc(env,token,op,data,transport);let result:any;
 if(url.pathname==='/company-lookup'&&request.method==='GET'){const auth=await call('lookup_permission');if(url.searchParams.get('country')!=='CZ')throw new RpcError(400,'country_unsupported');result=await companyLookup(auth.app_id,url.searchParams.get('ico')??'',transport);}
 else if(url.pathname==='/invoices'&&request.method==='POST'){active(env);const body=JSON.parse(new TextDecoder().decode(await bounded(request,1024*1024)));result=await call('invoice_create',{command:body,key:request.headers.get('Idempotency-Key')});return Response.json(result,{status:202});}
 else if(/^\/invoices\/[^/]+(?:\/pdf|\/deliver)?$/.test(url.pathname)){const [,,invoice_id,action]=url.pathname.split('/');if(!action&&request.method==='GET')result=await call('invoice_get',{invoice_id});else if(action==='pdf'&&request.method==='GET'){const a=await call('artifact_get',{invoice_id});return new Response((await privatePdf(env,a)).buffer as ArrayBuffer,{headers:{'Content-Type':'application/pdf','Cache-Control':'no-store','Content-Disposition':'attachment; filename="invoice.pdf"'}});}else if(action==='deliver'&&request.method==='POST'){active(env);result=await call('deliver',{invoice_id,key:request.headers.get('Idempotency-Key')});}else throw new RpcError(404,'not_found');}
 else if(/^\/customers\/[^/]+\/(billing-status|profile)$/.test(url.pathname)){const [,,customer_id,action]=url.pathname.split('/');if(action==='billing-status'&&request.method==='GET')result=await call('customer_status',{customer_id});else if(action==='profile'&&request.method==='GET')result=await call('profile_get',{customer_id});else if(action==='profile'&&request.method==='PUT')result=await call('profile_save',{...JSON.parse(new TextDecoder().decode(await bounded(request))),customer_id});else throw new RpcError(404,'not_found');}
 else if(url.pathname==='/events'&&request.method==='GET'){const cursor=url.searchParams.get('cursor')??'0';if(!/^\d{1,18}$/.test(cursor))throw new RpcError(400,'cursor_invalid');result=await call('events',{cursor});}
 else if(url.pathname==='/schedules'&&request.method==='GET')result=await call('schedule_list');
 else if(/^\/schedules\/[^/]+$/.test(url.pathname)&&request.method==='GET')result=await call('schedule_get',{schedule_id:url.pathname.split('/')[2]});
 else if(url.pathname==='/schedules'&&request.method==='POST'){active(env);result=await call('schedule_create',{...JSON.parse(new TextDecoder().decode(await bounded(request))),key:request.headers.get('Idempotency-Key')});}
 else if(/^\/schedules\/[^/]+$/.test(url.pathname)&&request.method==='PATCH'){result=await call('schedule_update',{...JSON.parse(new TextDecoder().decode(await bounded(request))),schedule_id:url.pathname.split('/')[2]});}
 else if(url.pathname==='/incidents'&&request.method==='GET')result=await call('incidents');else throw new RpcError(404,'not_found');
 return Response.json(result,{headers:{'Cache-Control':'no-store'}});
 }catch(error){const e=error as Error;return Response.json({error:e instanceof RpcError?e.message:e.message==='company_not_found'?'company_not_found':e.message==='ico_invalid'?'ico_invalid':'service_unavailable'},{status:e instanceof RpcError?e.status:e.message==='company_not_found'?404:e.message==='ico_invalid'?400:503});}},
 async scheduled(_event:unknown,env:Env){active(env);for(const w of workloads(env)){try{await drain(env,w,transport);}catch{/* Durable RPC queues retain failures; do not log financial payloads. */}}}
};}
async function bankRequest(w:Workload,path:string,body:unknown,transport:typeof fetch){const r=await transport(new URL(path,httpsOrigin(w.banksync_origin)),{method:body===undefined?'GET':'POST',redirect:'manual',signal:AbortSignal.timeout(10000),headers:{'X-Tenant-Secret':w.banksync_token,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});if(!r.ok){let code='banksync_unavailable';try{const v=await r.json() as any;if(['reference_conflict','reference_registry_locked','reference_exhausted','invalid_vs','reference_forbidden'].includes(v.error))code=v.error;}catch{}throw new RpcError(r.status,code);}return r.json() as Promise<any>;}
export async function invoiceBrand(env:Pick<Env,'BRANDS_JSON'>,appId:string):Promise<InvoiceBrand|undefined>{
 const configured=(JSON.parse(env.BRANDS_JSON??'{}') as Record<string,InvoiceBrand&{wordmark_paths_gzip?:string}>)[appId];if(!configured)return;
 if(!configured.wordmark_paths_gzip)return configured;
 const bytes=Uint8Array.from(atob(configured.wordmark_paths_gzip),c=>c.charCodeAt(0));const text=await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text();if(text.length>100000)throw Error('brand_invalid');
 return {...configured,wordmark_paths:JSON.parse(text)};
}
export async function drain(env:Env,w:Workload,transport:typeof fetch=fetch){
 const call=(op:string,data:unknown={})=>serviceRpc(env,w.token,op,data,transport);active(env);const brand=await invoiceBrand(env,w.app_id);
 try{const health=await bankRequest(w,`/bank-accounts/${w.bank_account_id}/account-health`,undefined,transport);await call('health',{...health,bank_account_id:w.bank_account_id});}catch{await call('health',{bank_account_id:w.bank_account_id,bank_observation_status:'unknown',bank_observed_through:null});}
 await call('schedule_sweep');
 for(const intent of await call('issue_list')){try{
  // Layout preflight before permanent numbering; confirmed parties loaded by RPC.
  const preview=await call('issue_preview',{invoice_id:intent.invoice_id});await renderInvoice(preview as Snapshot,brand);
  const reference=intent.reference_mode==='service'?await call('service_reference',{invoice_id:intent.invoice_id}):intent.reference_mode==='provided'?{reservation_id:'provided:'+intent.invoice_id,normalized_vs:intent.command.variable_symbol,source_ref:intent.source_ref,payload_hash:intent.payload_hash,physical_account_id:intent.physical_account_id,app_id:w.consumer_id}:await bankRequest(w,`/bank-accounts/${intent.bank_account_id}/payment-references`,{source_ref:intent.source_ref,payload_hash:intent.payload_hash,...(intent.command.variable_symbol?{variable_symbol:intent.command.variable_symbol}:{})},transport);await call('issue',{invoice_id:intent.invoice_id,reference});
 }catch(error){await call('issue_failed',{invoice_id:intent.invoice_id,code:error instanceof RpcError?error.message:'reference_or_preflight_unavailable'});}}
 if(env.INVOICE_ARTIFACTS)for(const row of await call('render_list')){try{const data=await renderInvoice(row.snapshot,brand),hash=await digest(data),key=`${w.app_id}/${row.invoice_id}/${RENDERER_VERSION}/${hash}.pdf`;await env.INVOICE_ARTIFACTS.put(key,data,{httpMetadata:{contentType:'application/pdf'},customMetadata:{sha256:hash}});const stored=await env.INVOICE_ARTIFACTS.get(key);if(!stored||await digest(new Uint8Array(await stored.arrayBuffer()))!==hash)throw Error('artifact_upload_integrity');await call('artifact_ready',{invoice_id:row.invoice_id,object_key:key,sha256:hash,renderer_version:RENDERER_VERSION,bytes:data.length});}catch{await call('artifact_failed',{invoice_id:row.invoice_id,code:'render_or_storage_failed'});}}
 await call('reconcile_sweep');await call('overdue_sweep');
 for(let n=0;n<5;n++){const row=await call('webhook_claim');if(!row)break;let outcome='retry';try{const url=httpsOrigin(row.callback_url);const hosts=(env.CALLBACK_HOSTS??'').split(',');if(!hosts.includes(url.hostname)||!w.webhook_keys[row.callback_key_id])throw Error('callback_configuration');const signature=await signInvoicingWebhook(row.body,row.id,w.webhook_keys[row.callback_key_id]);const r=await transport(url,{method:'POST',redirect:'manual',signal:AbortSignal.timeout(10000),headers:{'Content-Type':'application/json','X-Invoicing-Timestamp':signature.timestamp,'X-Invoicing-Delivery-Id':row.id,'X-Invoicing-Key-Id':row.callback_key_id,'X-Invoicing-Signature':signature.signature},body:row.body});if(r.ok){const receipt=await r.json() as any;if(receipt.ok===true&&receipt.receipt_version===1&&receipt.delivery_id===row.id)outcome='delivered';}else if(r.status!==429&&r.status<500)outcome='terminal';}catch{}await call('webhook_complete',{id:row.id,fence:row.fence,outcome});}
 await feedback(env,w,call,transport);
 if(env.ENVIRONMENT==='live'&&w.email_from&&w.email_configuration_set&&w.feedback_queue_url&&env.INVOICE_ARTIFACTS)for(let n=0;n<3;n++){
  const worker=crypto.randomUUID(),row=await call('email_claim',{worker});if(!row)break;const complete=(op:string,data:unknown={})=>call(op,{id:row.id,fence:row.fence,worker,...data as object});let started=false;
  try{const data=await privatePdf(env,row.artifact);if(row.artifact_hash!==row.artifact.sha256)throw Error('attachment_hash');const s=row.snapshot as Snapshot,subject=`${row.recipient_role==='owner'?'[Kopie] ':''}${s.brand_name}: faktura ${s.number}`;let binary='';for(const byte of data)binary+=String.fromCharCode(byte);
   await complete('email_begin');started=true;const response=await awsRequest(env,'ses','/v2/email/outbound-emails',JSON.stringify({FromEmailAddress:w.email_from,ConfigurationSetName:w.email_configuration_set,Destination:{ToAddresses:[row.recipient]},EmailTags:[{Name:'invoicing_app',Value:w.app_id},{Name:'invoicing_delivery_id',Value:row.id}],Content:{Simple:{Subject:{Data:subject,Charset:'UTF-8'},Body:{Text:{Data:`Faktura ${s.number}\nČástka: ${amountText(s.total_minor)} CZK\nSplatnost: ${s.due_on}\nÚčet: ${s.account.iban}\nVS: ${s.reference.normalized_vs}\nPDF v příloze. Kontakt: ${s.issuer.email}`,Charset:'UTF-8'}},Attachments:[{RawContent:btoa(binary),FileName:s.number+'.pdf',ContentType:'application/pdf',ContentDisposition:'ATTACHMENT',ContentTransferEncoding:'BASE64'}]}}}),transport);
   if(!response.ok)throw Error('provider_response_unknown');const receipt=await response.json() as any;if(!receipt.MessageId)throw Error('provider_response_unknown');await complete('email_accepted',{provider_id:receipt.MessageId});
  }catch{if(started)try{await complete('email_failure',{code:'provider_unknown'});}catch{}}
 }
}
const amountText=(v:string)=>`${BigInt(v)/100n}.${String(BigInt(v)%100n).padStart(2,'0')}`;
async function feedback(env:Env,w:Workload,call:(op:string,data?:unknown)=>Promise<any>,transport:typeof fetch){if(!w.feedback_queue_url||!env.AWS_ACCESS_KEY_ID)return;const u=httpsOrigin(w.feedback_queue_url);if(u.hostname!==`sqs.${env.AWS_REGION??'eu-central-1'}.amazonaws.com`)throw Error('feedback_queue_scope');const sqs=async(action:string,data:unknown)=>{const r=await awsRequest(env,'sqs','/',JSON.stringify(data),transport,{target:`AmazonSQS.${action}`,contentType:'application/x-amz-json-1.0'});if(!r.ok)throw Error('feedback_unavailable');return r.json() as Promise<any>;};const batch=await sqs('ReceiveMessage',{QueueUrl:u.href,MaxNumberOfMessages:5,WaitTimeSeconds:0});for(const message of batch.Messages??[]){try{let e=JSON.parse(message.Body);if(e.Type==='Notification')e=JSON.parse(e.Message);if(e.mail?.tags?.invoicing_app?.[0]!==w.app_id)continue;const state=({Send:'accepted',Delivery:'delivered',Bounce:'bounced',Complaint:'complaint',Reject:'failed'} as Record<string,string>)[e.eventType??e.notificationType];if(!state||e.mail.destination?.length!==1||!e.mail.messageId)continue;await call('email_feedback',{id:e.mail.tags.invoicing_delivery_id[0],event_id:await sha256(message.MessageId),state,provider_id:e.mail.messageId,recipient:e.mail.destination[0]});await sqs('DeleteMessage',{QueueUrl:u.href,ReceiptHandle:message.ReceiptHandle});}catch{}}}
export default createService();
