BEGIN;
CREATE SCHEMA invoicing;
CREATE SCHEMA invoicing_api;
DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='invoicing_executor') THEN CREATE ROLE invoicing_executor NOLOGIN NOSUPERUSER NOBYPASSRLS; END IF; IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='invoicing_gateway') THEN CREATE ROLE invoicing_gateway NOLOGIN NOSUPERUSER NOBYPASSRLS; END IF; END $$;
REVOKE ALL ON SCHEMA invoicing,invoicing_api FROM PUBLIC;
CREATE TABLE invoicing.applications(id text PRIMARY KEY,environment text NOT NULL CHECK(environment IN('simulation','live')),event_counter bigint NOT NULL DEFAULT 0,overdue_customer_cursor text,callback_url text,callback_key_id text,delivery_policy text NOT NULL DEFAULT 'automatic_customer_copy_owner' CHECK(delivery_policy IN('automatic_customer_copy_owner','owner_approval')));
CREATE TABLE invoicing.credentials(jti_hash text PRIMARY KEY,app_id text NOT NULL REFERENCES invoicing.applications(id),audience text NOT NULL DEFAULT 'invoicing-rpc',scopes text[] NOT NULL,expires_at timestamptz NOT NULL,revoked_at timestamptz);
CREATE TABLE invoicing.customers(app_id text NOT NULL REFERENCES invoicing.applications(id),id text NOT NULL,profile jsonb,profile_version integer NOT NULL DEFAULT 0,billing_version bigint NOT NULL DEFAULT 0,status_snapshot jsonb,PRIMARY KEY(app_id,id));
CREATE TABLE invoicing.profile_history(app_id text NOT NULL,customer_id text NOT NULL,version integer NOT NULL,profile jsonb NOT NULL,changed_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(app_id,customer_id,version),FOREIGN KEY(app_id,customer_id) REFERENCES invoicing.customers(app_id,id));
CREATE TABLE invoicing.receiving_accounts(app_id text NOT NULL,id text NOT NULL,iban text NOT NULL,physical_account_id text NOT NULL,bank_account_id integer NOT NULL,instance_id text NOT NULL,consumer_id text NOT NULL,activation_at timestamptz NOT NULL,verified boolean NOT NULL DEFAULT false,reference_mode text NOT NULL DEFAULT 'banksync' CHECK(reference_mode IN('service','banksync','provided')),observation_status text NOT NULL DEFAULT 'unknown' CHECK(observation_status IN('healthy','degraded','unknown')),health_as_of timestamptz,observed_through timestamptz,PRIMARY KEY(app_id,id));
CREATE TABLE invoicing.issuer_profiles(app_id text NOT NULL,id text NOT NULL,profile jsonb NOT NULL,account_id text NOT NULL,confirmed boolean NOT NULL DEFAULT false,tax_regime text NOT NULL CHECK(tax_regime IN('unconfirmed','non_vat')),due_days integer NOT NULL CHECK(due_days BETWEEN 1 AND 90),owner_email text NOT NULL,series_prefix text NOT NULL CHECK(series_prefix~'^[A-Z0-9-]{1,20}$'),PRIMARY KEY(app_id,id),FOREIGN KEY(app_id,account_id) REFERENCES invoicing.receiving_accounts(app_id,id));
CREATE TABLE invoicing.invoice_series(app_id text NOT NULL,issuer_id text NOT NULL,year integer NOT NULL,next_number bigint NOT NULL DEFAULT 1,PRIMARY KEY(app_id,issuer_id,year),FOREIGN KEY(app_id,issuer_id) REFERENCES invoicing.issuer_profiles(app_id,id));
CREATE TABLE invoicing.invoices(app_id text NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),customer_id text NOT NULL,issuer_id text NOT NULL,source_ref text NOT NULL,idempotency_key text NOT NULL,payload_hash text NOT NULL,command jsonb NOT NULL,issuance_state text NOT NULL DEFAULT 'awaiting_reference' CHECK(issuance_state IN('draft','awaiting_reference','blocked','issued','cancelled_draft')),artifact_state text NOT NULL DEFAULT 'pending' CHECK(artifact_state IN('pending','rendering','ready','failed')),delivery_state text NOT NULL DEFAULT 'pending',number text,issued_on date,due_on date,currency text NOT NULL CHECK(currency='CZK'),total_minor bigint NOT NULL CHECK(total_minor BETWEEN 1 AND 999999999999),allocated_minor bigint NOT NULL DEFAULT 0 CHECK(allocated_minor>=0 AND allocated_minor<=total_minor),payment_version integer NOT NULL DEFAULT 0,paid_at timestamptz,aggregate_version integer NOT NULL DEFAULT 1,snapshot jsonb,reference_id text,physical_account_id text,normalized_vs text,incident text,overdue_notified boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(app_id,id),UNIQUE(app_id,customer_id,source_ref),UNIQUE(app_id,idempotency_key),UNIQUE(app_id,number),FOREIGN KEY(app_id,customer_id) REFERENCES invoicing.customers(app_id,id),FOREIGN KEY(app_id,issuer_id) REFERENCES invoicing.issuer_profiles(app_id,id));
CREATE UNIQUE INDEX issued_reference_unique ON invoicing.invoices(physical_account_id,normalized_vs) WHERE reference_id IS NOT NULL;
CREATE TABLE invoicing.reference_counters(physical_account_id text PRIMARY KEY,next_vs bigint NOT NULL DEFAULT 1 CHECK(next_vs BETWEEN 1 AND 10000000000));
CREATE TABLE invoicing.payment_reference_claims(app_id text NOT NULL,invoice_id uuid NOT NULL,physical_account_id text NOT NULL,normalized_vs text NOT NULL,mode text NOT NULL,reservation_id text NOT NULL,PRIMARY KEY(physical_account_id,normalized_vs),UNIQUE(app_id,invoice_id),FOREIGN KEY(app_id,invoice_id) REFERENCES invoicing.invoices(app_id,id));
CREATE TABLE invoicing.invoice_lines(app_id text NOT NULL,invoice_id uuid NOT NULL,source_line_id text NOT NULL,description text NOT NULL,group_label text,quantity bigint NOT NULL CHECK(quantity>0),unit_minor bigint NOT NULL CHECK(unit_minor>=0),PRIMARY KEY(app_id,invoice_id,source_line_id),FOREIGN KEY(app_id,invoice_id) REFERENCES invoicing.invoices(app_id,id));
CREATE TABLE invoicing.invoice_artifacts(app_id text NOT NULL,invoice_id uuid NOT NULL,object_key text NOT NULL UNIQUE,sha256 text NOT NULL,renderer_version text NOT NULL,bytes integer NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(app_id,invoice_id),FOREIGN KEY(app_id,invoice_id) REFERENCES invoicing.invoices(app_id,id));
CREATE TABLE invoicing.schedules(app_id text NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),command jsonb NOT NULL,idempotency_key text NOT NULL,payload_hash text NOT NULL,revision integer NOT NULL DEFAULT 1,next_due_on date NOT NULL,anchor_on date NOT NULL,interval_kind text NOT NULL CHECK(interval_kind IN('month','year')),interval_count integer NOT NULL CHECK(interval_count BETWEEN 1 AND 120),ends_before date,status text NOT NULL DEFAULT 'active' CHECK(status IN('active','paused','cancelled')),pause_policy text NOT NULL CHECK(pause_policy IN('skip','defer')),PRIMARY KEY(app_id,id),UNIQUE(app_id,idempotency_key));
CREATE TABLE invoicing.schedule_revisions(app_id text NOT NULL,schedule_id uuid NOT NULL,revision integer NOT NULL,command jsonb NOT NULL,PRIMARY KEY(app_id,schedule_id,revision),FOREIGN KEY(app_id,schedule_id) REFERENCES invoicing.schedules(app_id,id));
CREATE TABLE invoicing.schedule_occurrences(app_id text NOT NULL,schedule_id uuid NOT NULL,occurrence date NOT NULL,invoice_id uuid NOT NULL,revision integer NOT NULL,PRIMARY KEY(app_id,schedule_id,occurrence),FOREIGN KEY(app_id,schedule_id) REFERENCES invoicing.schedules(app_id,id),FOREIGN KEY(app_id,invoice_id) REFERENCES invoicing.invoices(app_id,id));
CREATE TABLE invoicing.bank_inbox(app_id text NOT NULL,instance_id text NOT NULL,consumer_id text NOT NULL,delivery_id text NOT NULL,payload_hash text NOT NULL,receipt jsonb NOT NULL,PRIMARY KEY(instance_id,consumer_id,delivery_id));
CREATE TABLE invoicing.bank_movements(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),app_id text NOT NULL,instance_id text NOT NULL,physical_account_id text NOT NULL,movement_id text NOT NULL,currency text NOT NULL,amount_minor bigint NOT NULL,normalized_vs text,identity_kind text NOT NULL,reconciliation_required boolean NOT NULL DEFAULT true,unallocated_minor bigint NOT NULL,payload jsonb NOT NULL,UNIQUE(instance_id,physical_account_id,movement_id));
CREATE TABLE invoicing.payment_allocations(app_id text NOT NULL,movement_id uuid NOT NULL REFERENCES invoicing.bank_movements(id),invoice_id uuid NOT NULL,amount_minor bigint NOT NULL CHECK(amount_minor>0),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(movement_id,invoice_id),FOREIGN KEY(app_id,invoice_id) REFERENCES invoicing.invoices(app_id,id));
CREATE TABLE invoicing.integration_events(app_id text NOT NULL,event_id uuid NOT NULL DEFAULT gen_random_uuid(),cursor bigint NOT NULL,body jsonb NOT NULL,PRIMARY KEY(app_id,event_id),UNIQUE(app_id,cursor));
CREATE TABLE invoicing.webhook_outbox(app_id text NOT NULL,id uuid NOT NULL,event_id uuid NOT NULL,body text NOT NULL,state text NOT NULL DEFAULT 'pending' CHECK(state IN('pending','claimed','delivered','terminal')),attempts integer NOT NULL DEFAULT 0,next_attempt_at timestamptz NOT NULL DEFAULT now(),lease_until timestamptz,fence integer NOT NULL DEFAULT 0,PRIMARY KEY(app_id,id),FOREIGN KEY(app_id,event_id) REFERENCES invoicing.integration_events(app_id,event_id));
CREATE TABLE invoicing.delivery_outbox(app_id text NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),invoice_id uuid NOT NULL,dedupe_key text NOT NULL,recipient text NOT NULL,recipient_role text NOT NULL CHECK(recipient_role IN('customer','owner')),artifact_hash text NOT NULL,state text NOT NULL DEFAULT 'pending' CHECK(state IN('pending','approval_required','claimed','sending','accepted','delivered','bounced','complaint','failed','unknown','merged')),worker text,fence integer NOT NULL DEFAULT 0,lease_until timestamptz,provider_id text,incident text,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(app_id,id),UNIQUE(app_id,dedupe_key,recipient),FOREIGN KEY(app_id,invoice_id) REFERENCES invoicing.invoices(app_id,id));
CREATE TABLE invoicing.delivery_events(app_id text NOT NULL,event_id text NOT NULL,delivery_id uuid NOT NULL,event text NOT NULL,PRIMARY KEY(app_id,event_id),FOREIGN KEY(app_id,delivery_id) REFERENCES invoicing.delivery_outbox(app_id,id));
CREATE TABLE invoicing.suppressed_recipients(app_id text NOT NULL,recipient text NOT NULL,reason text NOT NULL,PRIMARY KEY(app_id,recipient));
CREATE TABLE invoicing.audit_events(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,app_id text NOT NULL,kind text NOT NULL,data jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
-- Invariants enforced below RPC, including privileged accidental mutation.
CREATE FUNCTION invoicing.freeze_invoice() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.issuance_state='issued' AND (NEW.command,NEW.snapshot,NEW.number,NEW.reference_id,NEW.total_minor,NEW.due_on,NEW.customer_id,NEW.issuer_id,NEW.issuance_state,NEW.app_id,NEW.id,NEW.payload_hash,NEW.source_ref,NEW.idempotency_key,NEW.issued_on,NEW.currency,NEW.physical_account_id,NEW.normalized_vs) IS DISTINCT FROM (OLD.command,OLD.snapshot,OLD.number,OLD.reference_id,OLD.total_minor,OLD.due_on,OLD.customer_id,OLD.issuer_id,OLD.issuance_state,OLD.app_id,OLD.id,OLD.payload_hash,OLD.source_ref,OLD.idempotency_key,OLD.issued_on,OLD.currency,OLD.physical_account_id,OLD.normalized_vs) THEN RAISE EXCEPTION 'issued_invoice_immutable'; END IF; RETURN NEW; END $$;
CREATE TRIGGER invoice_freeze BEFORE UPDATE ON invoicing.invoices FOR EACH ROW EXECUTE FUNCTION invoicing.freeze_invoice();
CREATE FUNCTION invoicing.no_delete() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'financial_history_immutable'; END $$;
CREATE FUNCTION invoicing.freeze_lines() RETURNS trigger LANGUAGE plpgsql SET search_path=invoicing,pg_catalog AS $$ BEGIN IF TG_OP='INSERT' THEN IF EXISTS(SELECT 1 FROM invoices WHERE app_id=NEW.app_id AND id=NEW.invoice_id AND issuance_state='issued') THEN RAISE EXCEPTION 'issued_lines_immutable';END IF;RETURN NEW;END IF;RAISE EXCEPTION 'financial_history_immutable';END $$;
CREATE TRIGGER line_freeze BEFORE INSERT OR UPDATE OR DELETE ON invoicing.invoice_lines FOR EACH ROW EXECUTE FUNCTION invoicing.freeze_lines();
CREATE TRIGGER artifact_freeze BEFORE UPDATE OR DELETE ON invoicing.invoice_artifacts FOR EACH ROW EXECUTE FUNCTION invoicing.no_delete();
CREATE TRIGGER reference_claim_no_delete BEFORE DELETE OR UPDATE ON invoicing.payment_reference_claims FOR EACH ROW EXECUTE FUNCTION invoicing.no_delete();
CREATE TRIGGER invoice_no_delete BEFORE DELETE ON invoicing.invoices FOR EACH ROW EXECUTE FUNCTION invoicing.no_delete();
CREATE TRIGGER allocation_no_delete BEFORE DELETE OR UPDATE ON invoicing.payment_allocations FOR EACH ROW EXECUTE FUNCTION invoicing.no_delete();
DO $$ DECLARE t text; BEGIN FOR t IN SELECT tablename FROM pg_tables WHERE schemaname='invoicing' LOOP EXECUTE format('ALTER TABLE invoicing.%I ENABLE ROW LEVEL SECURITY',t); IF t NOT IN('applications','credentials','audit_events','reference_counters') THEN EXECUTE format('CREATE POLICY app_scope ON invoicing.%I TO invoicing_executor USING(app_id=current_setting(''invoicing.app_id'',true)) WITH CHECK(app_id=current_setting(''invoicing.app_id'',true))',t); END IF; END LOOP; END $$;
CREATE POLICY reference_counter_scope ON invoicing.reference_counters TO invoicing_executor USING(EXISTS(SELECT 1 FROM invoicing.receiving_accounts r WHERE r.app_id=current_setting('invoicing.app_id',true) AND r.physical_account_id=reference_counters.physical_account_id)) WITH CHECK(EXISTS(SELECT 1 FROM invoicing.receiving_accounts r WHERE r.app_id=current_setting('invoicing.app_id',true) AND r.physical_account_id=reference_counters.physical_account_id));
DROP POLICY app_scope ON invoicing.payment_reference_claims;
CREATE POLICY reference_claim_scope ON invoicing.payment_reference_claims TO invoicing_executor USING(EXISTS(SELECT 1 FROM invoicing.receiving_accounts r WHERE r.app_id=current_setting('invoicing.app_id',true) AND r.physical_account_id=payment_reference_claims.physical_account_id)) WITH CHECK(app_id=current_setting('invoicing.app_id',true));
-- Bank facts are shared internally only for configured receiving accounts. APIs
-- expose scoped allocations, never this relation or foreign transaction payloads.
DROP POLICY app_scope ON invoicing.bank_movements;
CREATE POLICY physical_scope ON invoicing.bank_movements TO invoicing_executor
 USING(EXISTS(SELECT 1 FROM invoicing.receiving_accounts r WHERE r.app_id=current_setting('invoicing.app_id',true) AND r.physical_account_id=bank_movements.physical_account_id AND r.instance_id=bank_movements.instance_id))
 WITH CHECK(EXISTS(SELECT 1 FROM invoicing.receiving_accounts r WHERE r.app_id=current_setting('invoicing.app_id',true) AND r.physical_account_id=bank_movements.physical_account_id AND r.instance_id=bank_movements.instance_id));
-- Executor policies are also explicit for service configuration.
CREATE POLICY application_scope ON invoicing.applications TO invoicing_executor USING(id=current_setting('invoicing.app_id',true));
CREATE POLICY credential_scope ON invoicing.credentials TO invoicing_executor USING(true);
CREATE POLICY audit_scope ON invoicing.audit_events TO invoicing_executor USING(app_id=current_setting('invoicing.app_id',true)) WITH CHECK(app_id=current_setting('invoicing.app_id',true));
GRANT USAGE ON SCHEMA invoicing,invoicing_api TO invoicing_executor;
GRANT SELECT,INSERT,UPDATE ON ALL TABLES IN SCHEMA invoicing TO invoicing_executor;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA invoicing TO invoicing_executor;
ALTER DEFAULT PRIVILEGES IN SCHEMA invoicing REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA invoicing_api REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
COMMIT;
